wandb_version: 1

obs_format:
  desc: null
  value: relative_pos
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: accelerated_env
epochs:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699406857.603695
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
